export const services = [
    {   id:"1",
        color:"red"
    },
    {   id:"3",
        color:"blue"
    },
    {   id:"2",
        color:"black"
    },
    {   id:"4",
        color:"green"
    },
]


export const dotsVersions =[

    [
        {
            id:0,
            position:"-150%",
            color:"green"
        },
        {
            id:2,
            position:"10%",
            color:"black"
        },
        {
            id:3,
            position:"15%",
            color:"red"
        },
        {
            id:4,
            position:"50%",
            color:"red"
        },
        {
            id:5,
            position:"120%",
            color:"green"
        },
    ],


    [
        {
            id:0,
            position:"10%",
            color:"green"
        },
        {
            id:2,
            position:"15%",
            color:"black"
        },
        {
            id:3,
            position:"50%",
            color:"red"
        },
        {
            id:4,
            position:"120%",
            color:"red"
        },
        {
            id:5,
            position:"-150%",
            color:"green"
        },
    ],

    [
        {
            id:0,
            position:"15%",
            color:"green"
        },
        {
            id:2,
            position:"50%",
            color:"black"
        },
        {
            id:3,
            position:"120%",
            color:"red"
        },
        {
            id:4,
            position:"-150%",
            color:"red"
        },
        {
            id:5,
            position:"10%",
            color:"green"
        },
    ],

    [
        {
            id:0,
            position:"50%",
            color:"green"
        },
        {
            id:2,
            position:"120%",
            color:"black"
        },
        {
            id:3,
            position:"-150%",
            color:"red"
        },
        {
            id:4,
            position:"10%",
            color:"red"
        },
        {
            id:5,
            position:"15%",
            color:"green"
        },
    ],

    [
        {
            id:0,
            position:"120%",
            color:"green"
        },
        {
            id:2,
            position:"-150%",
            color:"black"
        },
        {
            id:3,
            position:"10%",
            color:"red"
        },
        {
            id:4,
            position:"15%",
            color:"red"
        },
        {
            id:5,
            position:"50%",
            color:"green"
        },
    ],
    
]